const raw = @import("raw");
const clap = @import("clap_zig");
const testing = @import("std").testing;
const feature = clap.plugin.feature;

test "plugin feature IDs" {
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_INSTRUMENT, feature.instrument);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_AUDIO_EFFECT, feature.audio_effect);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_NOTE_EFFECT, feature.note_effect);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_NOTE_DETECTOR, feature.note_detector);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_ANALYZER, feature.analyzer);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_SYNTHESIZER, feature.synthesizer);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_SAMPLER, feature.sampler);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_DRUM, feature.drum);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_DRUM_MACHINE, feature.drum_machine);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_FILTER, feature.filter);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_PHASER, feature.phaser);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_EQUALIZER, feature.equalizer);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_DEESSER, feature.deesser);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_PHASE_VOCODER, feature.phase_vocoder);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_GRANULAR, feature.granular);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_FREQUENCY_SHIFTER, feature.frequency_shifter);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_PITCH_SHIFTER, feature.pitch_shifter);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_DISTORTION, feature.distortion);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_TRANSIENT_SHAPER, feature.transient_shaper);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_COMPRESSOR, feature.compressor);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_EXPANDER, feature.expander);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_GATE, feature.gate);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_LIMITER, feature.limiter);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_FLANGER, feature.flanger);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_CHORUS, feature.chorus);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_DELAY, feature.delay);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_REVERB, feature.reverb);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_TREMOLO, feature.tremolo);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_GLITCH, feature.glitch);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_UTILITY, feature.utility);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_PITCH_CORRECTION, feature.pitch_correction);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_RESTORATION, feature.restoration);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_MULTI_EFFECTS, feature.multi_effects);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_MIXING, feature.mixing);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_MASTERING, feature.mastering);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_MONO, feature.mono);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_STEREO, feature.stereo);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_SURROUND, feature.surround);
    try testing.expectEqualStrings(raw.CLAP_PLUGIN_FEATURE_AMBISONIC, feature.ambisonic);
}
