const raw = @import("raw");
const clap = @import("clap_zig");
const testing = @import("std").testing;
const feature = clap.plugin.feature;

test "plugin feature IDs" {
    try testing.expectEqualStrings(feature.instrument, raw.CLAP_PLUGIN_FEATURE_INSTRUMENT);
    try testing.expectEqualStrings(feature.audio_effect, raw.CLAP_PLUGIN_FEATURE_AUDIO_EFFECT);
    try testing.expectEqualStrings(feature.note_effect, raw.CLAP_PLUGIN_FEATURE_NOTE_EFFECT);
    try testing.expectEqualStrings(feature.note_detector, raw.CLAP_PLUGIN_FEATURE_NOTE_DETECTOR);
    try testing.expectEqualStrings(feature.analyzer, raw.CLAP_PLUGIN_FEATURE_ANALYZER);
    try testing.expectEqualStrings(feature.synthesizer, raw.CLAP_PLUGIN_FEATURE_SYNTHESIZER);
    try testing.expectEqualStrings(feature.sampler, raw.CLAP_PLUGIN_FEATURE_SAMPLER);
    try testing.expectEqualStrings(feature.drum, raw.CLAP_PLUGIN_FEATURE_DRUM);
    try testing.expectEqualStrings(feature.drum_machine, raw.CLAP_PLUGIN_FEATURE_DRUM_MACHINE);
    try testing.expectEqualStrings(feature.filter, raw.CLAP_PLUGIN_FEATURE_FILTER);
    try testing.expectEqualStrings(feature.phaser, raw.CLAP_PLUGIN_FEATURE_PHASER);
    try testing.expectEqualStrings(feature.equalizer, raw.CLAP_PLUGIN_FEATURE_EQUALIZER);
    try testing.expectEqualStrings(feature.deesser, raw.CLAP_PLUGIN_FEATURE_DEESSER);
    try testing.expectEqualStrings(feature.phase_vocoder, raw.CLAP_PLUGIN_FEATURE_PHASE_VOCODER);
    try testing.expectEqualStrings(feature.granular, raw.CLAP_PLUGIN_FEATURE_GRANULAR);
    try testing.expectEqualStrings(feature.frequency_shifter, raw.CLAP_PLUGIN_FEATURE_FREQUENCY_SHIFTER);
    try testing.expectEqualStrings(feature.pitch_shifter, raw.CLAP_PLUGIN_FEATURE_PITCH_SHIFTER);
    try testing.expectEqualStrings(feature.distortion, raw.CLAP_PLUGIN_FEATURE_DISTORTION);
    try testing.expectEqualStrings(feature.transient_shaper, raw.CLAP_PLUGIN_FEATURE_TRANSIENT_SHAPER);
    try testing.expectEqualStrings(feature.compressor, raw.CLAP_PLUGIN_FEATURE_COMPRESSOR);
    try testing.expectEqualStrings(feature.expander, raw.CLAP_PLUGIN_FEATURE_EXPANDER);
    try testing.expectEqualStrings(feature.gate, raw.CLAP_PLUGIN_FEATURE_GATE);
    try testing.expectEqualStrings(feature.limiter, raw.CLAP_PLUGIN_FEATURE_LIMITER);
    try testing.expectEqualStrings(feature.flanger, raw.CLAP_PLUGIN_FEATURE_FLANGER);
    try testing.expectEqualStrings(feature.chorus, raw.CLAP_PLUGIN_FEATURE_CHORUS);
    try testing.expectEqualStrings(feature.delay, raw.CLAP_PLUGIN_FEATURE_DELAY);
    try testing.expectEqualStrings(feature.reverb, raw.CLAP_PLUGIN_FEATURE_REVERB);
    try testing.expectEqualStrings(feature.tremolo, raw.CLAP_PLUGIN_FEATURE_TREMOLO);
    try testing.expectEqualStrings(feature.glitch, raw.CLAP_PLUGIN_FEATURE_GLITCH);
    try testing.expectEqualStrings(feature.utility, raw.CLAP_PLUGIN_FEATURE_UTILITY);
    try testing.expectEqualStrings(feature.pitch_correction, raw.CLAP_PLUGIN_FEATURE_PITCH_CORRECTION);
    try testing.expectEqualStrings(feature.restoration, raw.CLAP_PLUGIN_FEATURE_RESTORATION);
    try testing.expectEqualStrings(feature.multi_effects, raw.CLAP_PLUGIN_FEATURE_MULTI_EFFECTS);
    try testing.expectEqualStrings(feature.mixing, raw.CLAP_PLUGIN_FEATURE_MIXING);
    try testing.expectEqualStrings(feature.mastering, raw.CLAP_PLUGIN_FEATURE_MASTERING);
    try testing.expectEqualStrings(feature.mono, raw.CLAP_PLUGIN_FEATURE_MONO);
    try testing.expectEqualStrings(feature.stereo, raw.CLAP_PLUGIN_FEATURE_STEREO);
    try testing.expectEqualStrings(feature.surround, raw.CLAP_PLUGIN_FEATURE_SURROUND);
    try testing.expectEqualStrings(feature.ambisonic, raw.CLAP_PLUGIN_FEATURE_AMBISONIC);
}
